DROP TABLE IF EXISTS Jazda_testowa;

DROP TABLE IF EXISTS Zakup;

DROP TABLE IF EXISTS Sprzeda¿;

DROP TABLE IF EXISTS Oferta;

DROP TABLE IF EXISTS Samochód;

DROP TABLE IF EXISTS Wersja;

DROP TABLE IF EXISTS Model;

DROP TABLE IF EXISTS Dostawca;

DROP TABLE IF EXISTS Klient;

DROP TABLE IF EXISTS Sprzedawca;

DROP TABLE IF EXISTS Osoba;

DROP TABLE IF EXISTS Jêzyki_obce;

DROP TABLE IF EXISTS Typ_nadwozia;

DROP TABLE IF EXISTS Producent;

